"""Configuration for the Telegram bot."""
import os
from dotenv import load_dotenv

load_dotenv()

# Bot configuration
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')

# Funny ridiculous styles for image editing
FUNNY_STYLES = [
    "as a Renaissance oil painting with dramatic lighting and classical poses",
    "as a 1980s glamour shot with feathered hair, neon colors, and laser background",
    "as a medieval knight in shining armor riding a unicorn",
    "as a superhero with a cape flying through the city",
    "as a Victorian-era aristocrat with elaborate clothing and powdered wig",
    "as a cyberpunk character with neon implants and futuristic gear",
    "as a pirate captain on a ship with a parrot on shoulder",
    "as a disco dancer from the 70s with afro and bell-bottoms",
    "as an astronaut floating in space surrounded by pizza slices",
    "as a rockstar on stage with wild hair and leather jacket",
    "as a wizard with a long beard, pointy hat, and magical staff",
    "as a cowboy in the Wild West with hat and lasso",
    "as a ninja warrior in action pose with katana",
    "as a zombie apocalypse survivor with tattered clothes",
    "as a Greek god/goddess on Mount Olympus with toga and laurel wreath",
    "as a steampunk inventor with goggles and brass gadgets",
    "as a mermaid/merman underwater with colorful tail",
    "as a vampire count in a gothic castle",
    "as a samurai warrior in traditional armor",
    "as an Egyptian pharaoh with golden headdress and hieroglyphics",
    "as a troll from internet memes lurking under a digital bridge",
    "as a chef frantically flipping pancakes in a cartoon kitchen",
    "as an alien disguised poorly as a human at a party",
    "as a cat wearing sunglasses lounging on a pile of cash",
    "as a giant banana running in a marathon",
    "as a detective with a trench coat and oversized magnifying glass in a noir scene",
    "as a circus clown juggling rubber chickens",
    "as a sumo wrestler ballet dancing on stage",
    "as a robot trying (and failing) to blend in at a masquerade ball",
    "as a secret agent escaping an explosion on a skateboard",
    "as a magician pulling an endless scarf from a hat",
    "as a baby riding a dinosaur in a prehistoric playground",
    "as a game show host giving away imaginary prizes",
    "as a gardener in a jungle-sized houseplant forest",
    "as a hamster DJ spinning records at a club",
    "as a time traveler confused by modern technology",
    "as a famous explorer discovering a new continent made of cheese",
    "as a selfie-obsessed ghost haunting a photo booth",
    "as a penguin sunbathing on a tropical beach",
    "as a racecar driver speeding in a bathtub",
    "as a luchador wrestling a giant sandwich in a packed arena",
    "as a beekeeper chased by emoji-shaped bees",
    "as a jellybean attending a business meeting",
    "as a librarian shushing dinosaurs in the reading room",
    "as a mad scientist glowing from a chemistry experiment gone wrong",
    "as a Viking fighting over the last slice of pizza",
    "as a yeti surfing down a mountain of spaghetti",
    "as a goldfish giving a TED Talk to other fish",
    "as a zombie trying to blend in at a yoga class",
    "as a literal couch potato binging TV shows",
    "as a secret agent penguin in a tuxedo sneaking through a party",
    "as a plumber fixing pipes underwater alongside fish friends",
    "as a wizard accidentally conjuring rubber ducks",
    "as a unicorn trying to squeeze into a phone booth",
    "as a squirrel hoarding Wi-Fi routers instead of acorns",
    "as a caveman inventing the first meme on a cave wall",
    "as a kangaroo bouncing on a trampoline at the Olympics",
    "as a Minotaur lost in a supermarket maze",
    "as a narwhal jousting with spaghetti noodles",
    "as a chef serving invisible soup to invisible guests",
    "as a superhero whose only power is making perfectly round pancakes",
    "as a pirate debating with a talking parrot over the last cookie",
    "as a llama doing stand-up comedy at an open mic night",
    "as a sandwich artist literally sculpting sandwiches into statues",
    "as a hamster weightlifting cotton swabs at the Olympics",
    "as a dragon roasting marshmallows with its breath indoors",
    "as a penguin ice fishing using a selfie stick",
    "as a hotdog vendor chased by a stampede of hungry ducks",
    "as an astronaut planting a flag on a giant floating donut",
    "as a raccoon DJ at a rooftop party with glow sticks",
    "as a snail racing in the Indy 500 with a custom shell",
    "as a detective dog sniffing out missing socks",
    "as a genie trying to grant wishes with malfunctioning magic",
    "as a potato ninja sneaking into the vegetable drawer",
    "as a cow breakdancing at a barn disco",
    "as a librarian organizing books while riding a skateboard",
    "as a sushi roll conducting a symphony orchestra",
    "as a spaceman lost in a sea of rubber duckies",
    "as a fairy godparent granting wishes with spaghetti wands",
    "as a squirrel hosting a reality TV show about acorn storage",
]

