"""Google Gemini API service for image generation."""
import random
import io
from typing import Tuple
from PIL import Image
from google import genai
from config import GOOGLE_API_KEY, FUNNY_STYLES


class GeminiService:
    """Service for interacting with Google Gemini API for image generation."""
    
    def __init__(self):
        """Initialize Gemini client."""
        self.client = genai.Client()
    
    def get_random_style(self) -> str:
        """Get a random funny style from the list."""
        return random.choice(FUNNY_STYLES)
    
    def edit_image(self, image_bytes: bytes, style: str) -> Tuple[Image.Image, str]:
        """
        Generate a transformed image using Google Gemini API with Imagen.
        
        Args:
            image_bytes: The original image as bytes
            style: The style description to apply
            
        Returns:
            Tuple of (generated_image_bytes, style_used)
        """
        try:
            # Load the image
            image = Image.open(io.BytesIO(image_bytes))
            
            # Create a detailed prompt for image generation
            prompt = (
                f"Generate an image: Transform the person or people in the image into {style}. "
                f"Keep his/their facial features recognizable but apply the style dramatically and humorously. "
                f"Make it funny, entertaining and visually striking. High quality, detailed."
            )
            
            # Generate image using Imagen through Gemini API
            # Use Gemini GenerativeModel's generate_content with image
            gemini_response = self.client.models.generate_content(
                model="gemini-2.5-flash-image",
                contents=[prompt, image],
            )

            image_part = [part for part in gemini_response.parts if part.inline_data is not None]
            if not image_part:
                raise Exception("No image generated by Gemini API")

            generated_image = image_part[0].as_image()
            
            return generated_image, style
            
        except Exception as e:
            raise Exception(f"Failed to generate image with Gemini: {str(e)}")
